-- Tetris Score Dummy Data
-- INSERT 문으로 한번에 모든 데이터 삽입

INSERT INTO scores (name, score, game_mode, is_item_mode, created_at, updated_at) VALUES
-- 싱글 모드 (isItemMode = false) 더미 데이터
('김민수', 15000, 'HARD', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('이영희', 14500, 'HARD', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('박철수', 13800, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('정수연', 13200, 'HARD', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('최지훈', 12900, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('강서윤', 12500, 'HARD', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('임동혁', 12000, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('윤채원', 11800, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('장민재', 11500, 'HARD', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('한소희', 11200, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('오준석', 10900, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('서하은', 10500, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('권태양', 10200, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('노지우', 9800, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('송민호', 9500, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('백아연', 9200, 'NORMAL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('황재현', 8900, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('유나영', 8500, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('안준혁', 8200, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('조은지', 7900, 'EASY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 아이템 모드 (isItemMode = true) 더미 데이터
('테트리스왕', 18500, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('블럭마스터', 17800, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('라인클리어', 16900, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('콤보신', 16200, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스피드런', 15700, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로게이머', 15300, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('아이템킹', 14800, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('퍼펙트', 14400, 'HARD', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('전략가', 13900, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('고수', 13500, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('베테랑', 13100, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('챌린저', 12700, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('달인', 12300, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('엘리트', 11900, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('숙련자', 11400, 'NORMAL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('중급자', 10900, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('초보탈출', 10400, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('연습생', 9900, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('도전자', 9400, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('입문자', 8900, 'EASY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


